# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\doc\gitpub\github_sunnybug\python\demo\xPyQTDemo\ui\DlgLog.ui'
#
# Created: Mon Jun 11 18:06:45 2012
#      by: PyQt4 UI code generator 4.7.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DlgLog(object):
    def setupUi(self, DlgLog):
        DlgLog.setObjectName(_fromUtf8("DlgLog"))
        DlgLog.setEnabled(True)
        DlgLog.resize(773, 719)
        self.verticalLayoutWidget_2 = QtGui.QWidget(DlgLog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 771, 716))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget_2)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 500))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 500))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabDownLog = QtGui.QWidget()
        self.tabDownLog.setObjectName(_fromUtf8("tabDownLog"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.tabDownLog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 40, 751, 41))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.edtDownByFileName = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.edtDownByFileName.setObjectName(_fromUtf8("edtDownByFileName"))
        self.horizontalLayout_3.addWidget(self.edtDownByFileName)
        self.chkCompressOnFinish = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.chkCompressOnFinish.setEnabled(True)
        self.chkCompressOnFinish.setChecked(False)
        self.chkCompressOnFinish.setObjectName(_fromUtf8("chkCompressOnFinish"))
        self.horizontalLayout_3.addWidget(self.chkCompressOnFinish)
        self.chkFuzzy = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.chkFuzzy.setChecked(True)
        self.chkFuzzy.setObjectName(_fromUtf8("chkFuzzy"))
        self.horizontalLayout_3.addWidget(self.chkFuzzy)
        self.chkGmlog = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.chkGmlog.setEnabled(True)
        self.chkGmlog.setChecked(False)
        self.chkGmlog.setObjectName(_fromUtf8("chkGmlog"))
        self.horizontalLayout_3.addWidget(self.chkGmlog)
        self.verticalLayoutWidget = QtGui.QWidget(self.tabDownLog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 90, 221, 381))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chkAllGroup = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.chkAllGroup.setChecked(False)
        self.chkAllGroup.setObjectName(_fromUtf8("chkAllGroup"))
        self.verticalLayout.addWidget(self.chkAllGroup)
        self.tvSvr = QtGui.QTreeView(self.verticalLayoutWidget)
        self.tvSvr.setObjectName(_fromUtf8("tvSvr"))
        self.verticalLayout.addWidget(self.tvSvr)
        self.layoutWidget = QtGui.QWidget(self.tabDownLog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 769, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.edtLogPath = QtGui.QLineEdit(self.layoutWidget)
        self.edtLogPath.setObjectName(_fromUtf8("edtLogPath"))
        self.horizontalLayout_7.addWidget(self.edtLogPath)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        self.edtDownSpeed = QtGui.QLineEdit(self.layoutWidget)
        self.edtDownSpeed.setMinimumSize(QtCore.QSize(50, 20))
        self.edtDownSpeed.setMaximumSize(QtCore.QSize(50, 20))
        self.edtDownSpeed.setInputMask(_fromUtf8(""))
        self.edtDownSpeed.setObjectName(_fromUtf8("edtDownSpeed"))
        self.horizontalLayout_7.addWidget(self.edtDownSpeed)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tabDownLog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(220, 90, 541, 131))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupSvrList = QtGui.QGroupBox(self.verticalLayoutWidget_3)
        self.groupSvrList.setObjectName(_fromUtf8("groupSvrList"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupSvrList)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 551, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2.addWidget(self.groupSvrList)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnDumpCmd = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnDumpCmd.setEnabled(True)
        self.btnDumpCmd.setCheckable(False)
        self.btnDumpCmd.setObjectName(_fromUtf8("btnDumpCmd"))
        self.horizontalLayout_4.addWidget(self.btnDumpCmd)
        self.btnImportLog = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnImportLog.setEnabled(True)
        self.btnImportLog.setCheckable(False)
        self.btnImportLog.setObjectName(_fromUtf8("btnImportLog"))
        self.horizontalLayout_4.addWidget(self.btnImportLog)
        self.btnMergeLog = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnMergeLog.setEnabled(True)
        self.btnMergeLog.setCheckable(False)
        self.btnMergeLog.setObjectName(_fromUtf8("btnMergeLog"))
        self.horizontalLayout_4.addWidget(self.btnMergeLog)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnAddTask = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnAddTask.setEnabled(True)
        self.btnAddTask.setCheckable(False)
        self.btnAddTask.setObjectName(_fromUtf8("btnAddTask"))
        self.horizontalLayout_2.addWidget(self.btnAddTask)
        self.btnClearTask = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnClearTask.setEnabled(True)
        self.btnClearTask.setCheckable(False)
        self.btnClearTask.setObjectName(_fromUtf8("btnClearTask"))
        self.horizontalLayout_2.addWidget(self.btnClearTask)
        self.btnDownLogByFileName = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnDownLogByFileName.setEnabled(True)
        self.btnDownLogByFileName.setCheckable(False)
        self.btnDownLogByFileName.setObjectName(_fromUtf8("btnDownLogByFileName"))
        self.horizontalLayout_2.addWidget(self.btnDownLogByFileName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tabDownLog, _fromUtf8(""))
        self.tabCheckLog = QtGui.QWidget()
        self.tabCheckLog.setObjectName(_fromUtf8("tabCheckLog"))
        self.treeViewWarnLog = QtGui.QTreeView(self.tabCheckLog)
        self.treeViewWarnLog.setGeometry(QtCore.QRect(0, 160, 761, 311))
        self.treeViewWarnLog.setObjectName(_fromUtf8("treeViewWarnLog"))
        self.label_5 = QtGui.QLabel(self.tabCheckLog)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 291, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tabCheckLog)
        self.label_6.setGeometry(QtCore.QRect(730, 40, 24, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tabCheckLog)
        self.label_7.setGeometry(QtCore.QRect(640, 40, 31, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.edtCheckLogMinute = QtGui.QLineEdit(self.tabCheckLog)
        self.edtCheckLogMinute.setGeometry(QtCore.QRect(674, 40, 50, 20))
        self.edtCheckLogMinute.setMinimumSize(QtCore.QSize(50, 20))
        self.edtCheckLogMinute.setMaximumSize(QtCore.QSize(50, 20))
        self.edtCheckLogMinute.setInputMask(_fromUtf8(""))
        self.edtCheckLogMinute.setObjectName(_fromUtf8("edtCheckLogMinute"))
        self.edtCheckLogPath = QtGui.QLineEdit(self.tabCheckLog)
        self.edtCheckLogPath.setGeometry(QtCore.QRect(60, 39, 573, 20))
        self.edtCheckLogPath.setObjectName(_fromUtf8("edtCheckLogPath"))
        self.label_8 = QtGui.QLabel(self.tabCheckLog)
        self.label_8.setGeometry(QtCore.QRect(6, 30, 48, 39))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.btnCheckLog = QtGui.QPushButton(self.tabCheckLog)
        self.btnCheckLog.setEnabled(True)
        self.btnCheckLog.setGeometry(QtCore.QRect(0, 70, 71, 25))
        self.btnCheckLog.setCheckable(False)
        self.btnCheckLog.setObjectName(_fromUtf8("btnCheckLog"))
        self.tabWidget.addTab(self.tabCheckLog, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.edtMsg = QtGui.QTextEdit(self.verticalLayoutWidget_2)
        self.edtMsg.setMinimumSize(QtCore.QSize(759, 100))
        self.edtMsg.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.edtMsg.setReadOnly(True)
        self.edtMsg.setObjectName(_fromUtf8("edtMsg"))
        self.verticalLayout_4.addWidget(self.edtMsg)

        self.retranslateUi(DlgLog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.edtLogPath, QtCore.SIGNAL(_fromUtf8("editingFinished()")), DlgLog.OnLogPathEditFinish)
        QtCore.QObject.connect(self.edtDownSpeed, QtCore.SIGNAL(_fromUtf8("editingFinished()")), DlgLog.OnDownSpeedEditFinish)
        QtCore.QObject.connect(self.btnImportLog, QtCore.SIGNAL(_fromUtf8("clicked()")), DlgLog.ImportLog)
        QtCore.QObject.connect(self.btnMergeLog, QtCore.SIGNAL(_fromUtf8("clicked()")), DlgLog.MergeLog)
        QtCore.QObject.connect(self.btnDumpCmd, QtCore.SIGNAL(_fromUtf8("clicked()")), DlgLog.OnBtnDumpCmd)
        QtCore.QObject.connect(self.treeViewWarnLog, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), DlgLog.OnDBClickedWarnLogList)
        QtCore.QObject.connect(self.tvSvr, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), DlgLog.OnSvrTreeClicked)
        QtCore.QObject.connect(self.btnAddTask, QtCore.SIGNAL(_fromUtf8("clicked()")), DlgLog.OnAddTask)
        QtCore.QObject.connect(self.btnClearTask, QtCore.SIGNAL(_fromUtf8("clicked()")), DlgLog.OnClearTask)
        QtCore.QObject.connect(self.btnDownLogByFileName, QtCore.SIGNAL(_fromUtf8("clicked()")), DlgLog.DownLogByFileName)
        QtCore.QObject.connect(self.btnCheckLog, QtCore.SIGNAL(_fromUtf8("clicked()")), DlgLog.OnBtnCheckLog)
        QtCore.QMetaObject.connectSlotsByName(DlgLog)

    def retranslateUi(self, DlgLog):
        DlgLog.setWindowTitle(QtGui.QApplication.translate("DlgLog", "对话框试程序", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DlgLog", "文件名", None, QtGui.QApplication.UnicodeUTF8))
        self.chkCompressOnFinish.setText(QtGui.QApplication.translate("DlgLog", "下载完压缩", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFuzzy.setText(QtGui.QApplication.translate("DlgLog", "模糊匹配", None, QtGui.QApplication.UnicodeUTF8))
        self.chkGmlog.setText(QtGui.QApplication.translate("DlgLog", "gmlog", None, QtGui.QApplication.UnicodeUTF8))
        self.chkAllGroup.setText(QtGui.QApplication.translate("DlgLog", "AllGroup", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DlgLog", "LOG目录:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DlgLog", "下载速度", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DlgLog", "KB/s", None, QtGui.QApplication.UnicodeUTF8))
        self.groupSvrList.setTitle(QtGui.QApplication.translate("DlgLog", "服务器", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDumpCmd.setText(QtGui.QApplication.translate("DlgLog", "生成命令行", None, QtGui.QApplication.UnicodeUTF8))
        self.btnImportLog.setText(QtGui.QApplication.translate("DlgLog", "导入", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMergeLog.setText(QtGui.QApplication.translate("DlgLog", "合并", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddTask.setText(QtGui.QApplication.translate("DlgLog", "加任务", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClearTask.setText(QtGui.QApplication.translate("DlgLog", "清任务", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDownLogByFileName.setText(QtGui.QApplication.translate("DlgLog", "开始", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDownLog), QtGui.QApplication.translate("DlgLog", "下载Log", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DlgLog", "目标服务器列表为config.py的g_lstFtpGroup", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DlgLog", "分钟", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DlgLog", "间隔", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DlgLog", "LOG目录:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCheckLog.setText(QtGui.QApplication.translate("DlgLog", "开始", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCheckLog), QtGui.QApplication.translate("DlgLog", "检查Log", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DlgLog = QtGui.QDialog()
    ui = Ui_DlgLog()
    ui.setupUi(DlgLog)
    DlgLog.show()
    sys.exit(app.exec_())

